version: '3.8'

services:
  # SERVIÇO DO MINIO
  minio:
    image: minio/minio:latest
    container_name: minio
    # Comando para iniciar o servidor MinIO e a interface de usuário (Console)
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio_data:/data
    healthcheck:
      test: curl --fail http://localhost:9000/minio/health/live || exit 1
      interval: 30s
      timeout: 20s
      retries: 3

  create-buckets:
    image: minio/mc
    container_name: mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb minio/bronze;
      /usr/bin/mc mb minio/silver;
      /usr/bin/mc mb minio/gold;
      echo 'Buckets bronze, silver e gold criados com sucesso.';
      "

  app:
    build: .
    command: python app/app.py
    volumes:
      - ./data:/data